### PR TITLE
Simplify deserialization implementation of FileTarget and add tests

### PR DESCRIPTION
**Pull request by QuarticCat**
See this issue for more details https://github.com/serde-rs/serde/issues/2031

### CODE REVIEW

**Comment by SuperCuber** [comment]
This looks like a significant improvement!

I'm away from a computer for a couple days, could you add a test where type=symbolic and append=something? It should fail (with a reasonably human-understandable error)

**Comment by QuarticCat** [comment]
@SuperCuber Done

**Review by SuperCuber — APPROVED** [review]

**Comment by SuperCuber** [comment]
Is the CI not running or am I just not seeing it in the app?

**Comment by QuarticCat** [comment]
@SuperCuber It seems that you need to manually allow the first-time CI.

**Comment by SuperCuber** [comment]
Yep, seems like that button only shows up in the browser :)

**Pull request merged**
