### PR TITLE
Revert completions with build.rs, generate in CI instead

### PR DESCRIPTION
**Pull request by SuperCuber**
Reverts SuperCuber/dotter#118

### CODE REVIEW

**Comment by SuperCuber** [comment]
@TD-Sky wdyt?

**Comment by TD-Sky** [comment]
We discussed the following about shell completions:
1. You don't like tracking generated files,
2. But newly generated files will break the check of `cargo publish`
3. And you wish to keep the check step.

May be Generating shell completions in CI better than doing it in the package building step of various Linux distributions? I'm not so sure. It seems that now it is one of the few answers.

**Comment by TD-Sky** [comment]
> Here is a help for everyone traps into the same problem like us.

As we've seen, the reverted PR failed finally cause `build.rs` affects the crate publication.

To be honest, I was haunted by this failure until I found the [cargo include field](https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields) which can specify the published files in crate.

I do it in my own crate [dagtoc](https://crates.io/crates/dagtoc) and it runs pretty much perfectly.

You need tow steps:
1. Ignore `completions/` in `.gitignore`.
2. Include the files you want to publish in your `Cargo.toml`.

Then the completions generation won't impact publishing to crates.io .

(@SuperCuber   I sent an email to you but it seems that it entered into your recycle bin, so here I am.)

**Comment by SuperCuber** [comment]
If we're ignoring completions anyways then it's still done in CI, so might as well keep what works 🤷 

Cool that this is possible though :)

**Pull request merged**
